# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Firebase hosting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: build app
      run: |
        npm ci
        npm run build --if-present
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: buid
        path: build

  deploy:
  
    name: Deploy
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: buid
        path: build
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
